name: Deploy to Vercel

on:
  push:
    branches:
      - backend-deployer  # your deployment branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
